### ISSUE TITLE
зачем вложенность? 

### ISSUE THREAD

**Issue by KuznetsovGleb** [yuralnik/frontend_test#23]
https://github.com/yuralnik/frontend_test/blob/bd52423d9136fe0347cf51f87ce853fd37029dc2/Maket%204/styles.css#L156

**Comment by yuralnik** [comment]
Я эту часть делал с Яриком. Он говорил, что так правильней

**Comment by KuznetsovGleb** [comment]
ты мне можешь объяснить зачем вложенность использовал?
